name: remote_team_task_board_flutter
description: "Remote Team Task Board - Flutter Frontend with Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4
  
  # HTTP Client
  dio: ^5.7.0
  http: ^1.2.2
  
  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # Navigation
  go_router: ^14.6.1
  
  # Form Validation
  formz: ^0.7.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  flutter_colorpicker: ^1.1.0
  
  # JSON Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  mockito: ^5.4.4
  
  # Coverage
  coverage: ^1.9.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
